name: Deploy to ConoHa VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build
      env:
        VITE_BASE_URL: https://convert.sho43.xyz

    - name: Create target directory on VPS
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          mkdir -p /var/www/vhosts/convert.sho43.xyz
          rm -rf /var/www/vhosts/convert.sho43.xyz/*

    - name: Deploy files to VPS using rsync
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          # Create a temporary directory for upload
          mkdir -p /tmp/convert-media-deploy
          
    - name: Upload files via SCP
      uses: appleboy/scp-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        source: "dist/*"
        target: "/tmp/convert-media-deploy/"
        strip_components: 1

    - name: Move files and set permissions
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          # Move files from temp to final location
          mv /tmp/convert-media-deploy/* /var/www/vhosts/convert.sho43.xyz/
          rm -rf /tmp/convert-media-deploy
          
          # Set permissions
          chmod -R 755 /var/www/vhosts/convert.sho43.xyz/
          
          # Create .htaccess for Apache SPA routing (if Apache is used)
          cat > /var/www/vhosts/convert.sho43.xyz/.htaccess << 'EOF'
          <IfModule mod_rewrite.c>
            RewriteEngine On
            RewriteBase /
            RewriteRule ^index\.html$ - [L]
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteRule . /index.html [L]
          </IfModule>
          
          # Cache control for static assets
          <IfModule mod_expires.c>
            ExpiresActive On
            ExpiresByType image/jpg "access plus 1 year"
            ExpiresByType image/jpeg "access plus 1 year"
            ExpiresByType image/gif "access plus 1 year"
            ExpiresByType image/png "access plus 1 year"
            ExpiresByType image/svg+xml "access plus 1 year"
            ExpiresByType text/css "access plus 1 year"
            ExpiresByType application/javascript "access plus 1 year"
            ExpiresByType application/font-woff2 "access plus 1 year"
          </IfModule>
          
          # Security headers
          <IfModule mod_headers.c>
            Header set X-Frame-Options "SAMEORIGIN"
            Header set X-Content-Type-Options "nosniff"
            Header set X-XSS-Protection "1; mode=block"
          </IfModule>
          EOF
          
          echo "Deployment completed successfully!"
          echo "Files deployed to: /var/www/vhosts/convert.sho43.xyz/"
          echo "Site should be accessible at: https://convert.sho43.xyz"